var HOMOPHONE_BANK = [
  { sentence: "Elle ___ mang\u00e9 une pomme.", correct: "a", wrong: ["\u00e0"], rule: "\u00ab a \u00bb = le verbe avoir (il avait) ; \u00ab \u00e0 \u00bb = pr\u00e9position." },
  { sentence: "Nous allons ___ la piscine.", correct: "\u00e0", wrong: ["a"], rule: "\u00ab a \u00bb = le verbe avoir (il avait) ; \u00ab \u00e0 \u00bb = pr\u00e9position." },
  { sentence: "Il ___ gagn\u00e9 le match.", correct: "a", wrong: ["\u00e0"], rule: "\u00ab a \u00bb = le verbe avoir (il avait) ; \u00ab \u00e0 \u00bb = pr\u00e9position." },
  { sentence: "Je pense ___ mes vacances.", correct: "\u00e0", wrong: ["a"], rule: "\u00ab a \u00bb = le verbe avoir (il avait) ; \u00ab \u00e0 \u00bb = pr\u00e9position." },
  { sentence: "Mon fr\u00e8re ___ deux chiens.", correct: "a", wrong: ["\u00e0"], rule: "\u00ab a \u00bb = le verbe avoir (il avait) ; \u00ab \u00e0 \u00bb = pr\u00e9position." },
  { sentence: "Elle habite ___ Paris.", correct: "\u00e0", wrong: ["a"], rule: "\u00ab a \u00bb = le verbe avoir (il avait) ; \u00ab \u00e0 \u00bb = pr\u00e9position." },
  { sentence: "Il pense ___ sa famille.", correct: "\u00e0", wrong: ["a"], rule: "\u00ab a \u00bb = le verbe avoir (il avait) ; \u00ab \u00e0 \u00bb = pr\u00e9position." },
  { sentence: "Ma soeur ___ oubli\u00e9 son livre.", correct: "a", wrong: ["\u00e0"], rule: "\u00ab a \u00bb = le verbe avoir (il avait) ; \u00ab \u00e0 \u00bb = pr\u00e9position." },
  { sentence: "Le ciel ___ bleu.", correct: "est", wrong: ["et"], rule: "\u00ab et \u00bb relie deux mots ; \u00ab est \u00bb = le verbe \u00eatre (il \u00e9tait)." },
  { sentence: "J'aime le chocolat ___ les bonbons.", correct: "et", wrong: ["est"], rule: "\u00ab et \u00bb relie deux mots ; \u00ab est \u00bb = le verbe \u00eatre (il \u00e9tait)." },
  { sentence: "Mon chat ___ tout noir.", correct: "est", wrong: ["et"], rule: "\u00ab et \u00bb relie deux mots ; \u00ab est \u00bb = le verbe \u00eatre (il \u00e9tait)." },
  { sentence: "Il court ___ il saute.", correct: "et", wrong: ["est"], rule: "\u00ab et \u00bb relie deux mots ; \u00ab est \u00bb = le verbe \u00eatre (il \u00e9tait)." },
  { sentence: "Ce livre ___ passionnant.", correct: "est", wrong: ["et"], rule: "\u00ab et \u00bb relie deux mots ; \u00ab est \u00bb = le verbe \u00eatre (il \u00e9tait)." },
  { sentence: "Le chien ___ le chat jouent.", correct: "et", wrong: ["est"], rule: "\u00ab et \u00bb relie deux mots ; \u00ab est \u00bb = le verbe \u00eatre (il \u00e9tait)." },
  { sentence: "Ma soeur ___ malade aujourd'hui.", correct: "est", wrong: ["et"], rule: "\u00ab et \u00bb relie deux mots ; \u00ab est \u00bb = le verbe \u00eatre (il \u00e9tait)." },
  { sentence: "Les enfants ___ dans le jardin.", correct: "sont", wrong: ["son"], rule: "\u00ab son \u00bb = d\u00e9terminant (le sien) ; \u00ab sont \u00bb = le verbe \u00eatre (ils \u00e9taient)." },
  { sentence: "Il a rang\u00e9 ___ cartable.", correct: "son", wrong: ["sont"], rule: "\u00ab son \u00bb = d\u00e9terminant (le sien) ; \u00ab sont \u00bb = le verbe \u00eatre (ils \u00e9taient)." },
  { sentence: "Mes amis ___ gentils.", correct: "sont", wrong: ["son"], rule: "\u00ab son \u00bb = d\u00e9terminant (le sien) ; \u00ab sont \u00bb = le verbe \u00eatre (ils \u00e9taient)." },
  { sentence: "Elle cherche ___ stylo.", correct: "son", wrong: ["sont"], rule: "\u00ab son \u00bb = d\u00e9terminant (le sien) ; \u00ab sont \u00bb = le verbe \u00eatre (ils \u00e9taient)." },
  { sentence: "Les voitures ___ gar\u00e9es dehors.", correct: "sont", wrong: ["son"], rule: "\u00ab son \u00bb = d\u00e9terminant (le sien) ; \u00ab sont \u00bb = le verbe \u00eatre (ils \u00e9taient)." },
  { sentence: "Ils ___ fini leurs devoirs.", correct: "ont", wrong: ["on"], rule: "\u00ab on \u00bb = pronom (il) ; \u00ab ont \u00bb = le verbe avoir (ils avaient)." },
  { sentence: "___ va au cin\u00e9ma ce soir.", correct: "On", wrong: ["Ont"], rule: "\u00ab on \u00bb = pronom (il) ; \u00ab ont \u00bb = le verbe avoir (ils avaient)." },
  { sentence: "Les \u00e9l\u00e8ves ___ un contr\u00f4le demain.", correct: "ont", wrong: ["on"], rule: "\u00ab on \u00bb = pronom (il) ; \u00ab ont \u00bb = le verbe avoir (ils avaient)." },
  { sentence: "Demain, ___ ira \u00e0 la mer.", correct: "on", wrong: ["ont"], rule: "\u00ab on \u00bb = pronom (il) ; \u00ab ont \u00bb = le verbe avoir (ils avaient)." },
  { sentence: "___ a sonn\u00e9 \u00e0 la porte.", correct: "On", wrong: ["Ont"], rule: "\u00ab on \u00bb = pronom (il) ; \u00ab ont \u00bb = le verbe avoir (ils avaient)." },
  { sentence: "Tu pr\u00e9f\u00e8res le th\u00e9 ___ le caf\u00e9 ?", correct: "ou", wrong: ["o\u00f9"], rule: "\u00ab ou \u00bb = ou bien (un choix) ; \u00ab o\u00f9 \u00bb = indique le lieu." },
  { sentence: "Le village ___ je suis n\u00e9 est petit.", correct: "o\u00f9", wrong: ["ou"], rule: "\u00ab ou \u00bb = ou bien (un choix) ; \u00ab o\u00f9 \u00bb = indique le lieu." },
  { sentence: "Tu viens ___ tu restes ?", correct: "ou", wrong: ["o\u00f9"], rule: "\u00ab ou \u00bb = ou bien (un choix) ; \u00ab o\u00f9 \u00bb = indique le lieu." },
  { sentence: "Voici la maison ___ habite ma grand-m\u00e8re.", correct: "o\u00f9", wrong: ["ou"], rule: "\u00ab ou \u00bb = ou bien (un choix) ; \u00ab o\u00f9 \u00bb = indique le lieu." },
  { sentence: "___ gar\u00e7on est tr\u00e8s poli.", correct: "Ce", wrong: ["Se"], rule: "\u00ab ce \u00bb = d\u00e9terminant (ce, cet) ; \u00ab se \u00bb accompagne un verbe (il se lave)." },
  { sentence: "Il ___ lave les mains.", correct: "se", wrong: ["ce"], rule: "\u00ab ce \u00bb = d\u00e9terminant (ce, cet) ; \u00ab se \u00bb accompagne un verbe (il se lave)." },
  { sentence: "Je n'aime pas ___ film.", correct: "ce", wrong: ["se"], rule: "\u00ab ce \u00bb = d\u00e9terminant (ce, cet) ; \u00ab se \u00bb accompagne un verbe (il se lave)." },
  { sentence: "Elle ___ prom\u00e8ne dans le parc.", correct: "se", wrong: ["ce"], rule: "\u00ab ce \u00bb = d\u00e9terminant (ce, cet) ; \u00ab se \u00bb accompagne un verbe (il se lave)." },
  { sentence: "___ mon meilleur ami.", correct: "C'est", wrong: ["Ces", "Ses"], rule: "\u00ab c'est \u00bb = cela est ; \u00ab ces \u00bb = d\u00e9terminant pluriel ; \u00ab ses \u00bb = les siens ; \u00ab s'est \u00bb = il s'est." },
  { sentence: "Il a rang\u00e9 ___ affaires.", correct: "ses", wrong: ["ces", "c'est"], rule: "\u00ab c'est \u00bb = cela est ; \u00ab ces \u00bb = d\u00e9terminant pluriel ; \u00ab ses \u00bb = les siens ; \u00ab s'est \u00bb = il s'est." },
  { sentence: "___ enfants jouent dehors.", correct: "Ces", wrong: ["Ses", "C'est"], rule: "\u00ab c'est \u00bb = cela est ; \u00ab ces \u00bb = d\u00e9terminant pluriel ; \u00ab ses \u00bb = les siens ; \u00ab s'est \u00bb = il s'est." },
  { sentence: "Il ___ bless\u00e9 au genou.", correct: "s'est", wrong: ["c'est", "ses"], rule: "\u00ab c'est \u00bb = cela est ; \u00ab ces \u00bb = d\u00e9terminant pluriel ; \u00ab ses \u00bb = les siens ; \u00ab s'est \u00bb = il s'est." },
  { sentence: "Regarde ___ voiture rouge.", correct: "la", wrong: ["l\u00e0", "l'a"], rule: "\u00ab la \u00bb = d\u00e9terminant ; \u00ab l\u00e0 \u00bb = le lieu ; \u00ab l'a \u00bb = le/la + verbe avoir." },
  { sentence: "Viens ___, s'il te pla\u00eet.", correct: "l\u00e0", wrong: ["la", "l'a"], rule: "\u00ab la \u00bb = d\u00e9terminant ; \u00ab l\u00e0 \u00bb = le lieu ; \u00ab l'a \u00bb = le/la + verbe avoir." },
  { sentence: "Il ___ vue hier soir.", correct: "l'a", wrong: ["la", "l\u00e0"], rule: "\u00ab la \u00bb = d\u00e9terminant ; \u00ab l\u00e0 \u00bb = le lieu ; \u00ab l'a \u00bb = le/la + verbe avoir." },
  { sentence: "Les enfants rangent ___ jouets.", correct: "leurs", wrong: ["leur"], rule: "\u00ab leur \u00bb devant un verbe est invariable ; \u00ab leurs \u00bb = d\u00e9terminant, plusieurs choses." },
  { sentence: "Je ___ ai donn\u00e9 un cadeau.", correct: "leur", wrong: ["leurs"], rule: "\u00ab leur \u00bb devant un verbe est invariable ; \u00ab leurs \u00bb = d\u00e9terminant, plusieurs choses." },
  { sentence: "Ils aiment ___ maison.", correct: "leur", wrong: ["leurs"], rule: "\u00ab leur \u00bb devant un verbe est invariable ; \u00ab leurs \u00bb = d\u00e9terminant, plusieurs choses." },
  { sentence: "Les \u00e9l\u00e8ves ont oubli\u00e9 ___ cahiers.", correct: "leurs", wrong: ["leur"], rule: "\u00ab leur \u00bb devant un verbe est invariable ; \u00ab leurs \u00bb = d\u00e9terminant, plusieurs choses." },
  { sentence: "Il ___ venir demain.", correct: "peut", wrong: ["peu", "peux"], rule: "\u00ab peu \u00bb = pas beaucoup ; \u00ab peut \u00bb = pouvoir (il) ; \u00ab peux \u00bb = pouvoir (je, tu)." },
  { sentence: "J'ai mang\u00e9 un ___ de pain.", correct: "peu", wrong: ["peut", "peux"], rule: "\u00ab peu \u00bb = pas beaucoup ; \u00ab peut \u00bb = pouvoir (il) ; \u00ab peux \u00bb = pouvoir (je, tu)." },
  { sentence: "Tu ___ m'aider ?", correct: "peux", wrong: ["peut", "peu"], rule: "\u00ab peu \u00bb = pas beaucoup ; \u00ab peut \u00bb = pouvoir (il) ; \u00ab peux \u00bb = pouvoir (je, tu)." },
  { sentence: "Elle ___ courir tr\u00e8s vite.", correct: "peut", wrong: ["peu", "peux"], rule: "\u00ab peu \u00bb = pas beaucoup ; \u00ab peut \u00bb = pouvoir (il) ; \u00ab peux \u00bb = pouvoir (je, tu)." },
  { sentence: "J'aime le sport ___ je d\u00e9teste courir.", correct: "mais", wrong: ["mes", "met"], rule: "\u00ab mais \u00bb = pourtant ; \u00ab mes \u00bb = d\u00e9terminant (les miens) ; \u00ab met/mets \u00bb = le verbe mettre." },
  { sentence: "___ parents sont gentils.", correct: "Mes", wrong: ["Mais", "Met"], rule: "\u00ab mais \u00bb = pourtant ; \u00ab mes \u00bb = d\u00e9terminant (les miens) ; \u00ab met/mets \u00bb = le verbe mettre." },
  { sentence: "Il ___ son manteau.", correct: "met", wrong: ["mes", "mais"], rule: "\u00ab mais \u00bb = pourtant ; \u00ab mes \u00bb = d\u00e9terminant (les miens) ; \u00ab met/mets \u00bb = le verbe mettre." },
  { sentence: "Je ___ la table.", correct: "mets", wrong: ["mes", "mais"], rule: "\u00ab mais \u00bb = pourtant ; \u00ab mes \u00bb = d\u00e9terminant (les miens) ; \u00ab met/mets \u00bb = le verbe mettre." },
  { sentence: "Il range ___ chambre.", correct: "sa", wrong: ["\u00e7a"], rule: "\u00ab sa \u00bb = d\u00e9terminant (la sienne) ; \u00ab \u00e7a \u00bb = cela." },
  { sentence: "___ me pla\u00eet beaucoup.", correct: "\u00c7a", wrong: ["Sa"], rule: "\u00ab sa \u00bb = d\u00e9terminant (la sienne) ; \u00ab \u00e7a \u00bb = cela." },
  { sentence: "Elle a perdu ___ cl\u00e9.", correct: "sa", wrong: ["\u00e7a"], rule: "\u00ab sa \u00bb = d\u00e9terminant (la sienne) ; \u00ab \u00e7a \u00bb = cela." },
  { sentence: "Range ___ tout de suite !", correct: "\u00e7a", wrong: ["sa"], rule: "\u00ab sa \u00bb = d\u00e9terminant (la sienne) ; \u00ab \u00e7a \u00bb = cela." },
  { sentence: "___ heure est-il ?", correct: "Quelle", wrong: ["Quel", "Qu'elle"], rule: "\u00ab quel/quelle \u00bb = d\u00e9terminant interrogatif (il s'accorde) ; \u00ab qu'elle \u00bb = que + elle." },
  { sentence: "Je crois ___ viendra.", correct: "qu'elle", wrong: ["quelle", "quel"], rule: "\u00ab quel/quelle \u00bb = d\u00e9terminant interrogatif (il s'accorde) ; \u00ab qu'elle \u00bb = que + elle." },
  { sentence: "___ est ton sport pr\u00e9f\u00e9r\u00e9 ?", correct: "Quel", wrong: ["Quelle", "Qu'elle"], rule: "\u00ab quel/quelle \u00bb = d\u00e9terminant interrogatif (il s'accorde) ; \u00ab qu'elle \u00bb = que + elle." },
  { sentence: "Il n'aime ___ les carottes ni les navets.", correct: "ni", wrong: ["n'y"], rule: "\u00ab ni \u00bb = n\u00e9gation (ni... ni...) ; \u00ab n'y \u00bb = ne + y." },
  { sentence: "Il ___ pense jamais.", correct: "n'y", wrong: ["ni"], rule: "\u00ab ni \u00bb = n\u00e9gation (ni... ni...) ; \u00ab n'y \u00bb = ne + y." }
];
